### PR TITLE
This should fix Manishearth#9

### PR DESCRIPTION
**Pull request by Annonomus-Penguin**
If you didn't read the title, this is to fix Manishearth#9.

I trimmed the strings but removed the code that was preventing blank popus to save. Is there a reason you did that? I'm guessing you tried to auto-save when clicking outside of the popup, but that doesn't work either.

Also, Atom removed trailing whtiespace in a file

Do I need to say anything else?

### CODE REVIEW

**Comment by Manishearth** [comment]
What if I didn't read the title _or_ the first line of the pull request.

You really should be more explicit in these things :p

Anyway, looks good to me. Thanks!

(There was a reason behind this, but it's no longer relevant, had to do with saving-when-mousing-out which isn't so easy to do in the new UI anyway)

**Comment by Annonomus-Penguin** [comment]
If you didn't read the title or the first line then I'd advise to flip a coin. Heads = no pull (leaving the git head the same), tails = pull (the current git head won't be the head anymore). :P

@Manishearth I understand what you were trying to do with the saving when mousing out, but what does the new UI have to do with this feature being broken?

If you wanted to differentiate a button click vs. a clicking out, you could have the button always add a space at the end of the textbox to ensure that it has *some* content. It's trimmed anyway before storing, so the user would never know. Then, you could check to make sure that there's a character (that is *including whitespace*) in the textbox before saving.

It would still save if someone typed a space in the textbox, so a boolean might be a better idea.

```
if(!buttonWasClicked && textbox.value.trim() = "") {
  return;
}
```

**Comment by Manishearth** [comment]
The older UI was easier to click out on, there was much more space.

**Comment by Annonomus-Penguin** [comment]
Wait... by clicking outside of the textbox (and still on the popup) or on the *page*? I think we're talking about two different things. If I remember correctly, I could click out of the page and it would save....

**Comment by Manishearth** [comment]
The former.

Clicking outside of the popup doesn't work, sadly

**Comment by Annonomus-Penguin** [comment]
@Manishearth I see how it works now...

I did some research and I found two ideas:

 - [This](http://stackoverflow.com/a/3910427/1512962)
 - Save whenever a user types *anything*

Performance for both of these things would be terrible... why do you have to be this way Chrome?

**Comment by Manishearth** [comment]
Yeah, I asked on StackOverflow when I ran across this.

http://stackoverflow.com/questions/22141907/is-there-any-way-to-detect-popup-close-for-a-chrome-extension-before-the-popup-i

Chrome's API is quite limited. A Firefox addon would be fun to write, though (extremely powerful API)

**Comment by Annonomus-Penguin** [comment]
I'll do some tests sometime... `onmouseout` looks promising.

Another idea would be to do this:

```
//On load
var intervalId = 0;
var timerSet = false;

//On keypress:
if(timerSet) {
  clearInterval(intervalId);
}
intervalId = setInterval(saveFunction, 10000);
timerSet = true;

//On save:
if(timerSet) {
  clearInterval(intervalId);
}
timerSet = false;
//Other save code
```

Maybe we *don't* want to save when a user clicks out. Sometimes people like to close a window if they make a mistake ("if I didn't click save, it didn't save it!")... although the data shouldn't be that critical.

**Pull request merged**
